server:
  port: 7001
  servlet:
   context-path: /eureka1
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:root@eureka1:7001/eureka1,http://admin:root@eureka2:7002/eureka2,http://admin:root@eureka3:7003/eureka3
  instance: # eureak实例定义
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称
spring:
  security:
    user:
      name: admin
      password: root

